services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    ports:
      - "3334:3306"
    volumes:
      - myVolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

volumes:
  myVolume:
    driver: local
